[package]
name = "bytevm"
description = "A simple bytecode virtual machine"
keywords = ["vm", "bytecode", "interpreter"]
license = "MIT"
repository = "https://github.com/burdockcascade/bytevm"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.26"