[package]
name = "bytevm"
description = "A simple bytecode virtual machine"
keywords = ["vm", "bytecode", "interpreter"]
categories = ["virtualization"]
license = "MIT"
repository = "https://github.com/burdockcascade/bytevm"
version = "0.3.0"
edition = "2024"

[dependencies]
log = "0.4.27"

[dev-dependencies]
simplelog = "0.12.2"