name: Publish
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
on:
  release:
    types: [published]
permissions:
  contents: read
  packages: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test
  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Publish
        run: cargo publish --dry-run
  publish:
    needs: [test, publish-dry-run]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Publish
        run: cargo publish